# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr_1d = np.arange(10)
arr_2d = arr_1d.reshape(2,5)
print(arr_2d)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [10]:
# Numpy's universal function numpy.vstack() is used for vertical stacking of array
# it takes a tuple of arrays as an argument and returns an ndarray.
# For vertical stacking number of element in each array must be same
x = np.arange(10)
y = np.arange(10,20)
print(np.vstack((x,y)))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [8]:
# Numpy's universal function numpy.hstack() is used for horizontally stacking of array
# it takes a tuple of arrays as an argument and returns an ndarray.
# Length of each array must be same for horizontal stacking.
x = np.arange(10).reshape(2,5)
y = np.arange(10,16).reshape(2,3)
print(np.hstack((x,y)))

[[ 0  1  2  3  4 10 11 12]
 [ 5  6  7  8  9 13 14 15]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [14]:
# flatten() methods can be used to conver ndarray to 1-d array
arr_3d = np.arange(24).reshape(2,3,4)
print(arr_3d)
one_d = arr_3d.flatten()
print("flatten ouput",one_d)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
flatten ouput [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [16]:
# flatten() Or ravel() methods can be used to conver ndarray to 1-d array
arr_4d = np.arange(48).reshape(2,2,3,4)
print(arr_4d)
print("flatten ouput",arr_4d.flatten())
print("rivel ouput",arr_4d.ravel())

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]
flatten ouput [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
rivel ouput [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [ ]:
# reshape() method can be used to convert 1-d array to higher-d array
# Dimensions must be the multple of the number of elements in the 1-d array
arr_1d_again = np.arange(24)
arr_2d_again = arr_1d_again.reshape(6,4)

## Question:7

### Create 5x5 an array and find the square of an array?

In [29]:
arr_5x5 = np.arange(25).reshape(5,5)
print(np.square(arr_5x5))

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [22]:
arr_5x6 = np.arange(30).reshape(5,6)
print(arr_5x6)
print("Mean along axis-0:",np.mean(arr_5x6,0))


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Mean along axis-0 [12. 13. 14. 15. 16. 17.]


## Question:9

### Find the standard deviation of the previous array in Q8?

In [24]:
sd = np.std(arr_5x6,0)
print("Standard Deviation:",sd)

Standard Deviation: [8.48528137 8.48528137 8.48528137 8.48528137 8.48528137 8.48528137]


## Question:10

### Find the median of the previous array in Q8?

In [27]:
md = np.median(arr_5x6,0)
print("median:",md)

median: [12. 13. 14. 15. 16. 17.]


## Question:11

### Find the transpose of the previous array in Q8?

In [28]:
trnps = arr_5x6.T
print("Transpose:",trnps)

Transpose: [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [36]:
#Creating a 4x4 matrix
arr_4x4 = np.arange(10,26).reshape(4,4)
#Displaying the matrix
print(arr_4x4)
#getting sum of diagonal elements
diag_sum = np.trace(arr_4x4)
# Displaying the diagonal sum
print(diag_sum)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
70


## Question:13

### Find the determinant of the previous array in Q12?

In [37]:
deter = np.linalg.det(arr_4x4)
print("Determinant:",deter)

Determinant: 7.099748146989094e-29


## Question:14

### Find the 5th and 95th percentile of an array?

In [38]:
fifth_percentile = np.percentile(arr_4d,5)
ninty_fifth_percentile = np.percentile(arr_4d,95)
print("5th Percentile:{0}\n95th Percentile:{1}".format(fifth_percentile,ninty_fifth_percentile))

5th Percentile:2.35
95th Percentile:44.65


## Question:15

### How to find if a given array has any null values?

In [41]:
# numpy provides a method isnan() to find null value in an array.
contains_null = np.array([5,3,0,4,np.nan])
print(np.isnan(contains_null))

[False False False False  True]
