# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np


2. Create a null vector of size 10 

In [2]:
null_vector = np.array(np.zeros(10),dtype = np.int) 
print(null_vector.)
print("Null vector of 10 elements: {0}".format(null_vector))

SyntaxError: invalid syntax (<ipython-input-2-7f316b926e93>, line 2)

3. Create a vector with values ranging from 10 to 49

In [45]:
vector_10to49 = np.array(range(10,50),dtype='i1')
print(vector_10to49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [12]:
print(vector_10to49.shape)

(40,)


5. Print the type of the previous array in question 3

In [13]:
print("Type of Vector is {0}".format(vector_10to49.dtype))

Type of Vector is int32


6. Print the numpy version and the configuration


In [22]:
print("Version of Installed NumPy: {0}".format(np.__version__))
print(np.show_config())

Version of Installed NumPy: 1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


7. Print the dimension of the array in question 3


In [23]:
print(vector_10to49.ndim)

1


8. Create a boolean array with all the True values

In [24]:
bool_Array = np.array(np.ones((5,3),dtype=bool))
print(bool_Array)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

9. Create a two dimensional array




In [32]:
twoD_Array =np.full((2,5),5)
print(twoD_Array)

[[5 5 5 5 5]
 [5 5 5 5 5]]


10. Create a three dimensional array



In [5]:
threeD_Array = np.array(np.arange(30)).reshape(3,2,5)
print(threeD_Array)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [31]:
vector = np.arange(10)
print("Vector {0}".format(vector))
reverse_vector = vector[10:0:-1]
print("Reversed Vector {0}".format(reverse_vector))

Vector [0 1 2 3 4 5 6 7 8 9]
Reversed Vector [9 8 7 6 5 4 3 2 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [20]:
null_vector_True =np.array(np.arange(10)==4,dtype = int)
print(null_vector_True)
print(null_vector_True.shape)

[0 0 0 0 1 0 0 0 0 0]
(10,)


13. Create a 3x3 identity matrix

In [38]:
identity_matrix = np.identity(3,dtype= 'i2')
print(identity_matrix.dtype)

int16


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [10]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr = arr.astype(float)
print(arr.dtype)


int32
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [5]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
product = arr1 * arr2
print(product)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [53]:
comparison = arr1 == arr2
print(comparison)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [11]:
np_arr = np.arange(10)
odd_verifier = (np_arr%2!=0) #validating the odd numeber with modulus operator this will return an array of False(not odd) and True(odd)
arr_odd_number = np_arr[odd_verifier] #extract the odd number from the array by using boolean indexing
print(arr_odd_number)

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [12]:
# print(np_arr)
np_arr[odd_verifier] = -1
# print(np_arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [14]:
arr = np.arange(10)
print(arr)
arr[5:9] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [21]:
def onse_border(n,m= None):
    '''
    creates a 2D array with ones on the border and zeros inside
    n(rows) is compulsory
    m(cols) is optional
    '''
    if m == None:
        m = n
    arr2d = np.ones((n,m),dtype= 'int8')
    arr2d[1:n-1,1:m-1]=0
    return arr2d


arrTwoD =onse_border(3,4)
print(arrTwoD)

[[1 1 1 1]
 [1 0 0 1]
 [1 1 1 1]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [3]:
arr2d = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
# Replacing the desired value
arr2d[1,1]=12
arr2d


array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [4]:
arr3d = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
arr3d[arr3d<7] = 64
print(arr3d)

[[64 64 64 64 64 64]
 [ 7  8  9 10 11 12]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [13]:
array2D = np.arange(10,dtype = 'u2').reshape(2,5)
slice_1st_1D = array2D[0:1,:] # Slicing the First 1-D Array
print(slice_1st_1D)

[[0 1 2 3 4]]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [26]:
arrayTwo_D = np.arange(10,dtype = 'u2').reshape(2,5)
slice_2nd_1D = arrayTwo_D[1:len(arrayTwo_D),:] # Slicing the 2nd 1-D Array
print(slice_2nd_1D)

[[5 6 7 8 9]]


5

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [29]:
arrayTwo_D = np.arange(10,dtype = 'u2').reshape(2,5)
slice_3rdCol = arrayTwo_D[0:2,2] # Slicing the 2rd column with 1st 2 rows
print(slice_3rdCol)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [47]:
arr_rnd_10x10 = np.random.rand(10,10)*10 # Generates the random number 0-10(exclusive)
arr_min_val = arr_rnd_10x10.min() # Extract the minimum value 
arr_max_val = arr_rnd_10x10.max() # Extract the maximum value
print("Minimum={0}\nMaximum:{1}".format(arr_min_val,arr_max_val))


Minimum=0.04950769517467202
Maximum:9.988480759572493


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [109]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_items = np.intersect1d(a,b)
print(common_items)

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [114]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# This method finds common value between two given arrays and returns
# 1-d array of common items --> when return_indices = False
# [common_items,common position in arr1, common position in arr2] --> when return_indices = True
common_items = np.intersect1d(a,b,return_indices=True)
print("Common Positions in a ={0}\nCommon Positions in b ={1}".format(common_items[1],common_items[2]))

Common Positions in a =[1 5]
Common Positions in b =[1 5]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [146]:
names = np.array([ 'Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
mask = names !='Will'
# print("names:\n{0}\n\nData:\n{1}\n\nBooleanArray:\n{2}\n\nSelectedData:\n{3}".format(names,data,mask,data[mask]))
print("SelectedData:\n{0}".format(data[mask]))

SelectedData:
[[-1.89201376  0.26355732 -0.50586359 -1.17901445]
 [-0.13310822  0.20665018 -0.30020718 -1.95488996]
 [ 0.15463968 -1.21006018 -0.28083715 -1.34900877]
 [-1.00043177 -0.00349545  0.54497839  0.35580543]
 [ 0.25580088 -0.4639455   1.50482533 -1.57945235]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [145]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
mask = (names =='Will') | (names == 'Joe')
# print("names:\n{0}\n\nData:\n{1}\n\nBooleanArray:\n{2}\n\nSelectedData:\n{3}".format(names,data,~mask,data[~mask]))
print("SelectedData:\n{0}".format(data[~mask]))

SelectedData:
[[ 0.54454128 -0.81517034 -0.14127509 -0.06680249]
 [-0.08043487  0.78057722  1.12709868  0.33056461]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [148]:
arr_2d_5x3 = np.arange(1,16).reshape(5,3)
print(arr_2d_5x3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [150]:
arr_2x2x4 = np.arange(1,17).reshape(2,2,4)
print(arr_2x2x4)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


33. Swap axes of the array you created in Question 32

In [166]:
arr_2x2x4.swapaxes(0,1)

16

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [190]:
arr_10_size = np.random.rand(2,5)
sqr_result = np.sqrt(arr_10_size)
print(sqr_result)
filtered_data =np.where(sqr_result<0.5,0,sqr_result)
print(filtered_data)

[[0.40272486 0.76396623 0.41110272 0.7029168  0.88491151]
 [0.86631721 0.93212326 0.52065862 0.96395759 0.15040549]]
[[0.         0.76396623 0.         0.7029168  0.88491151]
 [0.86631721 0.93212326 0.52065862 0.96395759 0.        ]]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [196]:
rnd1_arry_r12 = np.random.randint(0,12,(2,6))
rnd2_arry_r12 = np.random.randint(0,12,(2,6))
rnd3_max = np.maximum(rnd1_arry_r12,rnd2_arry_r12)
print(rnd1_arry_r12)
print(rnd2_arry_r12)
print("*"*10)
print(rnd3_max)


[[ 8  8  2  9 10  0]
 [ 5  7  6  9  1  3]]
[[ 2  1  8  7  5  4]
 [ 4  5 11  3  9 10]]
**********
[[ 8  8  8  9 10  4]
 [ 5  7 11  9  9 10]]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [206]:
names = np.array(['Kate','Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique_names = np.unique(names) # returns the sorted unique array
print(unique_names)


['Bob' 'Joe' 'Kate' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [245]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
# finds the index in a of common elements 
b_element_index_in_a = np.intersect1d(a,b,return_indices=True)[1]
d =np.delete(a,b_element_index_in_a) # deletes the element of b presented in a 
print(d)


[4]
[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [254]:
sampleArray = np.array([34,43,73,82,22,12,53,94,66])
newColumn = np.array([10,10,10])
sampleArray = np.delete(sampleArray,2) # deletes the coloumn 2
sampleArray = np.insert(sampleArray,2,newColumn) # inserts the new colomn at given location
print(sampleArray)

[34 43 10 10 10 82 22 12 53 94 66]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [176]:
x = np.array([1., 2., 3., 4., 5., 6.]) 
y = np.array([6., 23., -1, 7, 8, 9])
dot_result = x.dot(y)
print(dot_result)

171.0


40. Generate a matrix of 20 random values and find its cumulative sum

In [175]:
matrix_20 = np.arange(20).reshape(2,10)
cumulative_sum = matrix_20.cumsum()
print(cumulative_sum)

[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]
