# Numpy Practice


In [44]:
import numpy as np
arr1 = np.random.randn(3,4) # creates a 2-d array with random signed number
arr2= (np.absolute(arr1*2)).astype('i2') # convertes the generated array to binary array.
print(arr1)
print(arr2)
print("\u001b[32m")
print("Mathematical Operations with ndarrays")

# vectorize Multiplication
print(arr2*arr2)

[[ 1.56932007 -0.46891702  1.21952207  0.24450975]
 [ 0.21257488  0.91112602  0.2386867  -1.30123951]
 [-1.47585067  0.39457025 -1.83300342  2.21145785]]
[[3 0 2 0]
 [0 1 0 2]
 [2 0 3 4]]

Mathematical Operations with ndarrays
[[ 9  0  4  0]
 [ 0  1  0  4]
 [ 4  0  9 16]]


# Array Creation

In [28]:
import numpy as np
# np.array() method is the simplest way to create ndarray
np_arr = np.array(())
np_asarr = np.asarry(np_arr)
np_empt = np.empty((2,5))
np_arr1 = np.arange(21)
print("np_arr:",np_arr)
print('np_asarr',np_asarr)
print('np_arr1',np_arr1)
print(np_empt)
np_arrfl = np.full_like(np_asarr,10,order='F')
print("Arr_Full",np_arrfl)
np_eye = np.eye(3,dtype=bool)
print("Eye",np_eye, sep='\n')
np_arr.data

AttributeError: module 'numpy' has no attribute 'asarry'