# Numpy Practice


In [44]:
import numpy as np
arr1 = np.random.randn(3,4) # creates a 2-d array with random signed number
arr2= (np.absolute(arr1*2)).astype('i2') # convertes the generated array to binary array.
print(arr1)
print(arr2)
print("\u001b[32m")
print("Mathematical Operations with ndarrays")

# vectorize Multiplication
print(arr2*arr2)

[[ 1.56932007 -0.46891702  1.21952207  0.24450975]
 [ 0.21257488  0.91112602  0.2386867  -1.30123951]
 [-1.47585067  0.39457025 -1.83300342  2.21145785]]
[[3 0 2 0]
 [0 1 0 2]
 [2 0 3 4]]

Mathematical Operations with ndarrays
[[ 9  0  4  0]
 [ 0  1  0  4]
 [ 4  0  9 16]]


# Array Creation

In [2]:
import numpy as np
# np.array() method is the simplest way to create ndarray
np_arr = np.array(())
np_asarr = np.asarray(np_arr)
np_empt = np.empty((2,5))
np_arr1 = np.arange(21)
print("np_arr:",np_arr)
print('np_asarr',np_asarr)
print('np_arr1',np_arr1)
print(np_empt)
np_arrfl = np.full_like(np_asarr,10,order='F')
print("Arr_Full",np_arrfl)
np_eye = np.eye(3,dtype=bool)
print("Eye",np_eye, sep='\n')
np_arr.data

np_arr: []
np_asarr []
np_arr1 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1.23574142e-311 1.77863633e-322 0.00000000e+000 0.00000000e+000
  6.79038653e-313]
 [7.11172819e-038 7.48418598e-067 6.80899911e-091 9.14559487e-043
  2.22522648e-306]]
Arr_Full []
Eye
[[ True False False]
 [False  True False]
 [False False  True]]


# Slicing and Indexing

In [99]:
import numpy as np
arr_4d = np.array(np.arange(20)).reshape(2,2,5)
print("Dimensions",arr_4d.ndim)
print(help(arr_4d.strides))
print("\u001b[42;2m")
print(arr_4d[1,0]>10)

Dimensions 3
Help on tuple object:

class tuple(object)
 |  tuple(iterable=(), /)
 |  
 |  Built-in immutable sequence.
 |  
 |  If no argument is given, the constructor returns an empty tuple.
 |  If iterable is specified the tuple is initialized from iterable's items.
 |  
 |  If the argument is a tuple, the return value is the same object.
 |  
 |  Built-in subclasses:
 |      asyncgen_hooks
 |      UnraisableHookArgs
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __iter_